Question
========

<br/>

En un estudio se han medido las siguientes variables:

<br/>

Tabla 1: **Variables recogidas**

```{r table-simple, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
require(pander)
panderOptions('table.split.table', Inf)

my.data <- "
| id  | sex | age | sit_ocup | tad | tas | htamed | coltot | hta | 
| --- |:---:| :---:|  :---:|  :---:| :---:| :---:| :---:| :---:|
| 1 | 1 | 69 | 2 | 91 | 144 | 0 | 260 | 1 | 
| 2 | 1 | 58 | 1 | 87 | 136 | 0 | 226 | 1 | 
| 3 | 0 | 62 | 5 | 73 | 148 | 1 | 174 | 1 | 
| 4 | 1 | 47 | 5 | 78 | 122 | 0 | 186 | 0 | 
| 5 | 0 | 39 | 2 | 77 | 125 | 0 | 259 | 0 | 
| 6 | 1 | 43 | 3 | 71 | 118 | 0 | 250 | 0 | 
| 7 | 0 | 42 | 5 | 70 | 115 | 0 | 202 | 0 | 
| 8 | 1 | 45 | 5 | 87 | 126 | 1 | 236 | 1 | 
| 9 | 0 | 45 | 5 | 91 | 135 | 0 | 228 | 1 | 
| 10 | 0 | 45 | 1 | 75 | 125 | 0 | 251 | 0 | 
| 11 | 1 | 42 | 5 | 79 | 137 | 0 | 203 | 0 | 
| 12 | 1 | 38 | 4 | 87 | 132 | 0 | 222 | 0 | 
| . | . | . | . | . | . | . | . | . | 
| . | . | . | . | . | . | . | . | . | 
| . | . | . | . | . | . | . | . | . | 
| . | . | . | . | . | . | . | . | . | 
| n | 0 | 55 | 5 | 87 | 126 | 1 | 245 | 0 |
"
pander(my.data, style = 'rmarkdown')

```

<br/>

Donde:

* **id**: Número consecutivo identificador del participante
* **sex**: Sexo del participante, con los siguientes códigos,
    * 0 = mujer
    * 1 = hombre
* **age**: Edad del participante
* **sit_ocup**: Situación laboral, con los siguientes códigos,
    * 1 = Autónomo
    * 2 = Trabajador por cuenta ajena
    * 3 = Empresario
    * 4 = Parado
    * 5 = Jubilado
    * 6 = Otros
* **tad**: Presión Arterial Diastólica 
* **tas**: Presión Arterial Sistólica
* **htamed**: Toma tratamiento antihipertensivo, con los siguientes códigos,
    * 0 = No
    * 1 = Si
* **coltot**: Colesterol Total
* **hta**: Hipertensión, con los siguientes códigos,
    * 0 = No
    * 1 = Si

¿Cuál de las siguientes respuestas es **FALSA**?

Answerlist
----------
* La variable **sit_ocup** es cualitativa (o categórica) ordinal
* La variable **id** debería tener ``n'' valores diferentes
* La variables **sex**, **htamed** y **hta** son cualitativas (o categóricas) dicotómicas
* Las variables **tas** y **tad** son cuantitativas (o numéricas) continuas y ya que miden ``lo mismo'' (presión arterial) en dos situaciones diferentes (en sístole y en diástole) podrían considerarse datos apareados
* Las variables **age**, **tas**, **tad** y **coltot son cuantitativas (o numéricas) continuas


Solution
========
En la variable **id**, "n" es un acrónimo que utiliza para indicar el tamaño de muestra. Si el identificador es correlativo, debería tener "n" valores diferentes 

En la variable **sit_ocup** no hay un criterio para decidir un orden (p.e. ¿autónomo va antes o después que parado?)



Answerlist
----------
* Falso
* Correcto
* Correcto
* Correcto
* Correcto


Meta-information
================
exname: Tipo de variables
extype: schoice
exsolution: 10000
exshuffle: 5
